Pull request for project "Building with Backgrounds and Gradients"
bruna-genz/apple-webpage-clone pull request #1
Opened 2019-08-16 19:12 UTC by bruna-genz

2019-08-17 08:18 UTC, Oghenebrume50 commented
Reviewing....

2019-08-17 11:45 UTC, Oghenebrume50 requested changes
Hi @bruna-genz  good start on this project, the UI looks okay but there are a few changes that should be made. **outlined below**
The navbar should be centred

2019-08-17 12:01 UTC, Oghenebrume50 requested changes
Stickler is not working yet.
Also validate the html and fix all errors and warnings

Do these things and submit for another review :pray:

2019-08-17 12:01 UTC, Oghenebrume50 commented on index.html
>                          <il><a href="#">iPod</a></il>
I think you have a typo here, these are li tags not il

2019-08-17 12:01 UTC, Oghenebrume50 commented on index.html
> +            </header>
the content  of this header tag are links (to other articles or #)

2019-08-17 12:01 UTC, Oghenebrume50 commented on index.html
>                  <il class="little-picture-one"><a></a></il>
you could put a div in the a tags and set the href value of a to # this way, you can still set the background-image, but it will be on the div. a tags are used for links, they shouldn't be empty.

2019-08-19 17:49 UTC, samgaco requested changes
### Hi @bruna-genz :vulcan_salute: 

### Good job :+1: You have implemented all the changes indicated by the TSE correctly, hence you are approved :clap: 

Things to do **before merging to the master branch:**

* **[OPTIONAL]** You could add the "play" icon at the right side of "Watch the "Your Verse" film and explore the stories" using for[ font awesome](https://fontawesome.com/icons?d=gallery) for example.
* **[OPTIONAL]** You can try to add the American flag icon at the same height the rest of the links are.
* **[OPTIONAL]** Please check about HTML semantic elements and try to implement some more of them on your project. (What about the `<main>` tag? ) 

### Please, consider those points above before merging to the master branch. And Congratulations on having your first solo project approved :tada: :clap:

2019-08-19 17:49 UTC, samgaco commented on index.html
> -        <article class="billbord">
You could enclose the dominant content of your body within `<main>` tags :smiley:

2019-08-20 14:34 UTC, merged